In [1]:
import torch
x = torch.tensor([3.0])
y = torch.tensor([2.0])

x + y, x * y, x / y, x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [2]:
x = torch.arange(4)

In [3]:
x[3]

tensor(3)

In [4]:
len(x) , x.shape

(4, torch.Size([4]))

### 矩阵转置

In [5]:
A = torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [6]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [7]:
# 对称矩阵的转置等于自己
B = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
B,B==B.T

(tensor([[1, 2, 3],
         [2, 0, 4],
         [3, 4, 5]]),
 tensor([[True, True, True],
         [True, True, True],
         [True, True, True]]))

In [8]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 通过分配新内存，将A的一个副本分配给B
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [9]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [10]:
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [11]:
x = torch.arange(4,dtype = torch.float32)
x

tensor([0., 1., 2., 3.])

In [12]:
y = torch.ones(4, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

### 矩阵向量积

In [13]:
A.shape, x.shape, torch.mv(A, x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

In [14]:
# 矩阵乘法，点积 in 矩阵向量积 in 矩阵乘法 向下兼容
B = torch.ones(4,3)
torch.mm(A,B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

## 范数 norm

线性代数中：
* 最常用的运算符
* 将向量映射导标量的函数$f$。
两个性质：
  * $f(\alpha x)=|\alpha|f(x).$
  * $f(x+y)\le f(x)+f(y).$
  * $f(x)\ge 0.$ 


最后一个性质，等号满足条件： $\forall i,[x]_i=0 \iff f(x)=0.$

$L_2$范数定义：

$$
\Vert{x}\Vert_2=\sqrt{\sum\limits^n_{i=1}x^2_i},
$$

In [15]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

更一般的范数定义：

$$
\Vert{x}\Vert_p = \left(\sum\limits_{i=1}^n \vert{x_i}\vert^p \right)^{1/p}
$$

### 佛罗贝尼乌斯范数 Frobenius norm

$$
\Vert{X}\Vert_F=\sqrt{\sum\limits^m_{i=1}\sum\limits^n_{j=1}x^2_{ij}}
$$

等同于，将矩阵中所有元素组成一条Vector，再对其求$L_2$范数

In [16]:
torch.norm(torch.ones((4, 9)))

tensor(6.)

## 范数与目标
*最大化* 分配给观测数据的概率; *最小化* 预测和真实观测之间的距离

![](https://pic.imgdb.cn/item/61a1d5922ab3f51d910fa1aa.jpg)