In [24]:
import torch

x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

在计算 $\frac{\partial y}{\partial x}$ 之前，需要存储梯度的内存

不能在每次更新参数的时候，都分配内存

In [25]:
x.requires_grad_(True)  # 等价于 `x = torch.arange(4.0, requires_grad=True)`
x.grad  # 默认值是None

In [26]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [27]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [28]:
x.grad == 4 * x

tensor([True, True, True, True])

In [29]:
6# 在默认情况下，PyTorch 会累积梯度，我们需要清除之前的值
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

### 非标量变量的反向传播

In [30]:
# 对非标量调用`backward`需要传入一个`gradient`参数，该参数指定微分函数关于`self`的梯度。在我们的例子中，我们只想求偏导数的和，所以传递一个1的梯度是合适的
x.grad.zero_()
y = x * x
# 等价于y.backward(torch.ones(len(x)))
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

#### 分离计算

In [31]:
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [32]:
x

tensor([0., 1., 2., 3.], requires_grad=True)